# docker-compose.yml
services:
  mysql-iprevsantos:
    image: mysql:8.0
    container_name: mysql_iprevsantos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iprev123
      MYSQL_DATABASE: iprev_dados
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
      
  app:
    build: .  # Constrói a imagem a partir do Dockerfile na pasta atual
    container_name: python_iprevsantos
    restart: always
    ports:
      - "8501:8501"  # Mapeia a porta do Streamlit
      - "8502:8502"  # Mapeia a porta do Streamlit
      - "8888:8888"  # Mapeia a porta do Jupyter Notebook

    volumes:
      - .:/app  # Mapeia a pasta atual para /app dentro do container
    depends_on:
      - mysql-iprevsantos # Garante que o banco de dados inicie antes da aplicação

volumes:
  mysql_data:
